<templateSet group="Kotlin">
  <template name="LogHelper" value=" LogHelper.logError(LogHelper.LogType.ERROR, &quot;&quot;, &quot;&quot;, error,false)" description="Write error to log" toReformat="false" toShortenFQNames="true">
    <context>
      <option name="KOTLIN_CLASS" value="true" />
      <option name="KOTLIN_STATEMENT" value="true" />
      <option name="KOTLIN_TOPLEVEL" value="true" />
    </context>
  </template>
  <template name="apicall" value=" val result = safeApiResult { $endpoint$.await() }&#10;        when (result) {&#10;            is Result.Success -&gt; {                &#10;                return &#10;            }&#10;            &#10;            is Result.Error -&gt; {&#10;                return &#10;            }&#10;        }" description="" toReformat="false" toShortenFQNames="true">
    <variable name="endpoint" expression="" defaultValue="" alwaysStopAt="true" />
    <context>
      <option name="KOTLIN_STATEMENT" value="true" />
    </context>
  </template>
  <template name="withContextMain" value=" withContext(Dispatchers.Main){&#10; &#10; }" description="" toReformat="false" toShortenFQNames="true">
    <context>
      <option name="KOTLIN_STATEMENT" value="true" />
    </context>
  </template>
  <template name="withContextIO" value=" withContext(Dispatchers.IO){&#10; &#10; }" description="" toReformat="false" toShortenFQNames="true">
    <context>
      <option name="KOTLIN_STATEMENT" value="true" />
    </context>
  </template>
  <template name="trycatch" value="        try {&#10;&#10;        } catch (ex: java.lang.Exception) {&#10;&#10;        }" description="try-catch block" toReformat="false" toShortenFQNames="true">
    <context>
      <option name="KOTLIN_STATEMENT" value="true" />
    </context>
  </template>
</templateSet>